% X = s1(:,1);
% Y = s1(:,2);
% Dx = vars1(:,1);
% Dy = vars1(:,2);
% mx = means1(:,1);
% my = means1(:,2);
% Cov = cov(s1);
% x = linspace(-10,10,200);
% y = linspace(-10,10,200);
% [X,Y] = meshgrid(x,y);
% T=[X(:) Y(:)];
% Z=mvnpdf(T,means1,sigma1);
% mesh(X,Y,reshape(Z,200,200));
% xlabel('x');
% ylabel('y');
% zlabel('f1(x,y)');
% title('Empirical pdf');

X = s2(:,1);
Y = s2(:,2);
Dx = vars2(:,1);
Dy = vars2(:,2);
mx = means2(:,1);
my = means2(:,2);
Cov = cov(s2);
x = linspace(-10,10,200);
y = linspace(-10,10,200);
[X,Y] = meshgrid(x,y);
T=[X(:) Y(:)];
Z=mvnpdf(T,means2,sigma2);
mesh(X,Y,reshape(Z,200,200));
xlabel('x');
ylabel('y');
zlabel('f2(x,y)');
title('Empirical pdf');
